const crypto = require("crypto"); // it is  node.js module  which is present in node.js docs and many more r also present there 
// const crypto = require("node:crypto");  m-2 
console.log("hello sabhi ko")
var x = 3;
var y = 5;
// use of sync in it : never use sync as it is responsible for blocking of main threads 
crypto.pbkdf2Sync("password","salt",500000,50,"sha512");
console.log("first key generated by sync ");
// pbkdf2: this crypto is also async and managed by libuv
crypto.pbkdf2("password","salt",500000,50,"sha512",(err, key)=>{
    console.log("key is generated"); 

});
function domultiply(x,y){
    const ress = x*y;
    return ress;
    
    }
    var z = domultiply(x,y);
    console.log("multiply give us", z);
    console.log("end of it ");
